### PR TITLE
Enforce `@TargetLocations` meta-annotation

### PR DESCRIPTION
**Pull request by AndrewShf**
Once https://github.com/eisop/checker-framework/pull/339 lands in opprop/checker-framework, this PR updates CFI.

### CODE REVIEW

**Review by wmdietl — CHANGES_REQUESTED** [review]
@AndrewShf Some of the discussions we had in https://github.com/eisop/checker-framework/pull/339 apply to this PR as well. Please take another pass through these changes.

**Comment by AndrewShf** [comment]
This recent failure is due do wrong choice of CheckerFramework version
`git clone -b enforce-targetlocations -q --single-branch --depth 1 https://github.com/AndrewShf/checker-framework.git /home/runner/work/checker-framework-inference/checker-framework-inference/../checker-framework`

As seen in the pipeline log file, when building CFI, it chose the eisop version enforce-targetlocations branch CheckerFramework as the dependency. However, CFI is a bit outdated and still needs opprop version CheckerFramework as the dependency. Delete `enforce-targetlocations` branch in eisop CF would help, as build script will pick the opprop master branch at this time.

**Comment by AndrewShf** [comment]
Oh, I still need to sync the eisop targetlocations changes to this opprop master branch to make the CI pass...

**Comment by Ao-senXiong** [comment]
I will cherry pick these commits as I am updating opprop to 3.39 now.

**Pull request closed without merging**
