### PR TITLE
Update from typetools 2020-04-23

### PR DESCRIPTION
**Pull request by xingweitian**
Today typetools released version 3.3.0. We need a regular update.

### CODE REVIEW

**Comment by wmdietl** [comment]
Regarding JDK 11: in that setting, we now parse JDK 11 source files instead of relying on a pre-compiled annotated JDK.
Maybe this is done twice, once with the real ATF and once, completely pointlessly, with the inference ATF.
Can you please look at
https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java#L412 and make sure that that only happens for the real ATF?

**Comment by zcai1** [comment]
@xingweitian @wmdietl 
We have a memory leak here:
Screenshot from 2020-04-23 02-21-53

Basically, `elementToBoundType` is a static field in `QualifierDefaults`, which, in this specific case, has elements with reference to the `AttributionTaskListener` in `AbstractTypeProcessor`, and thus lead to all checkers cannot be GCed. I did a simple experiment by clearing the cache after each test, and all tests were able to pass without OOM (I set the heap size to 512M).

So these are some of the fixes I can think of:
1. If running multiple annotation processors in one session only appears in testing, we can simply add a `clearCache()` to `QualifierDefaults`, and call it in a `@After` function.
2. We can also try to unsubscribe the listener after the processor finished its job, but I couldn't find a good place to make the call (`typeProcessingOver()` in `AbstractTypeProcessor` doesn't always work properly). Also, this method is not perfect if there are other paths from `elementToBoundType` to any checkers.
3. It'd be great if each checker (annotation processor) has its life-cycle, then we will have a good place to clear the cache.

Any thoughts?

**Comment by zcai1** [comment]
> Regarding JDK 11: in that setting, we now parse JDK 11 source files instead of relying on a pre-compiled annotated JDK.
> Maybe this is done twice, once with the real ATF and once, completely pointlessly, with the inference ATF.
> Can you please look at
> https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java#L412 and make sure that that only happens for the real ATF?

I don't think we are parsing the source files twice. After adding some breakpoints, I observed the files being parsed once in each `javac -processor` call.

The memory leak above should be the cause of all OOM errors, and parsing files failed because it couldn't allocate memory from the heap.

**Comment by wmdietl** [comment]
@zcai1 Thanks for looking into this issue! `elementToBoundType` is set as a `CollectionUtils.createLRUCache(CACHE_SIZE);` with a current cache size of 300.
Does `elementToBoundType` grow beyond the 300 maximum size?
Why is this only happening on Java 11?

> Update: I found the "fix" in CF https://github.com/typetools/checker-framework/blob/master/build.gradle#L721

Thanks for tracking that down!
I would definitely prefer finding a proper solution to this.

**Comment by xingweitian** [comment]
WOW, nice catch! Thanks a lot!

**Comment by xingweitian** [comment]
According to @zcai1's finding, I just tested and all tests passed if we add `forkEvery(1)` to CFI's `build.gradle`.

**Comment by wmdietl** [comment]
> According to @zcai1's finding, I just tested and all tests passed if we add `forkEvery(1)` to CFI's `build.gradle`.

@xingweitian Yes, please do that so that we can merge this PR.
@zcai1 If you're interested, it would be nice to fix the underlying issue that requires the use of `forkEvery(1)`.

**Comment by xingweitian** [comment]
One project, `JLargeArrays`, which is in our benchmark using by downstream projects, cannot compile in JDK11. The reason is: some packages, e.g., `sun.misc.Cleaner` has been moved to a new place since JDK9. Also, the last update of this project was in 2014, maybe it is not a good choice for being part of the benchmark.

I am going to remove it from the benchmark. Then this PR can be merged.

**Comment by zcai1** [comment]
> @zcai1 Thanks for looking into this issue! `elementToBoundType` is set as a `CollectionUtils.createLRUCache(CACHE_SIZE);` with a current cache size of 300.
> Does `elementToBoundType` grow beyond the 300 maximum size?
> Why is this only happening on Java 11?
> 
> > Update: I found the "fix" in CF https://github.com/typetools/checker-framework/blob/master/build.gradle#L721
> 
> Thanks for tracking that down!
> I would definitely prefer finding a proper solution to this.

After adding this piece of code to `QualifierDefaults`, I noticed that a new `QualifierDefaults` is loaded for each test case in Java 8, but `QualifierDefaults` is only loaded once in Java 11.

I guess it's either because we are using `javac.jar` in Java 8, or because Java 11 has a different class-loading strategy.

**Comment by zcai1** [comment]
> > @zcai1 Thanks for looking into this issue! `elementToBoundType` is set as a `CollectionUtils.createLRUCache(CACHE_SIZE);` with a current cache size of 300.
> > Does `elementToBoundType` grow beyond the 300 maximum size?
> > Why is this only happening on Java 11?
> > > Update: I found the "fix" in CF https://github.com/typetools/checker-framework/blob/master/build.gradle#L721
> > 
> > 
> > Thanks for tracking that down!
> > I would definitely prefer finding a proper solution to this.
> 
> After adding this piece of code to `QualifierDefaults`, I noticed that a new `QualifierDefaults` is loaded for each test case in Java 8, but `QualifierDefaults` is only loaded once in Java 11. All `elementToBoundType`s can be garbage collected after the test case is finished.
> 
> I guess it's either because we are using `javac.jar` in Java 8, or because Java 11 has a different class-loading strategy.

**Comment by xingweitian** [comment]
@wmdietl @zcai1 I have merged this pull request and opened an issue #266 for the possible future discussion.

**Pull request merged**
