### PR TITLE
Refactor ConstraintManager's API - createConstraint and addConstraint

### PR DESCRIPTION
**Pull request by topnessman**
Refactor logic of `ConstraintManager` to move "validation logic" into `addXXXConstraint()` and let `createXXXConstraint()` only create corresponding `Constraint`.

### CODE REVIEW

**Comment by wmdietl** [comment]
The `createXXXConstraint` methods are public and supposedly for use by clients. Shouldn't all the verification logic be in the `createXXConstraint` methods and the `addXXXConstraint` methods delegate to them? I.e. what is the benefit of this change over what we have at the moment?

**Comment by topnessman** [comment]
`addXXXConstraint()` is adding must-be-satisfied `XXXConstraint` to solver.
New `ImplicationConstraint` uses `Constraints` in `assumptions`, but those `Constraints` are just `Constraint` which may or may not be satisfied. If we validate when call `createSubtypeConstraint()`, i.e. subtype relationship between two slots, and we call with `@Top` <: `@Bottom`, `checker.report()` causes it to exit and wouldn't create `SubtypeConstraint`, but we should get it in this case.

**Comment by jyluo** [comment]
> we should get it in this case.

Why?

`[False and otherConstraints] ---> conclusion`  is always true.  If you encode `@Top` <: `@Bottom` as an assumption into the solver, then it is as good as not encoding this implication all together. Perhaps the logic that's required is that you check every assumption in the list prior to `new ImplicationConstraint(...)` call, and if any assumption is always false then don't create the implication.

**Comment by topnessman** [comment]
I think we are saying the same thing- if one/some of the assumptions is false, we still can generate the `ImplicationConstraint`, and it doesn't really matter we generate this `ImplicationConstraint` or not. As you said, the implication is always true.

But right now, `ConstraintManager` will directly exit if you call `createSubtypeConstraint(@Top, @Bottom)` because when it creates `SubtypeConstraint`, it validates that two slots are really subtypes if both of them are `ConstantSlots`. But what I'm saying is that, `ConstraintManager` shouldn't exit in this case, as you can always create implications like: `false -> true`.

**Comment by wmdietl** [comment]
That explanation makes more sense. Can you add a general comment to the class javadoc explaining this distinction between `addXXX` and `createXXX` methods?
Maybe different method names would also make the distinction clearer, e.g. `enforceXXX` and `createXXX`?

Should some of the normalizations still happen for both and be written just in the `createXXX` methods? For example, `addSubtypeConstraint` sometimes gets normalized to equality constraints. Why shouldn't this be done in both cases?

**Comment by wmdietl** [comment]
We discussed this PR again today and @jyluo will implement an alternative that might make all of us happy.

**Pull request closed without merging**
