### PR TITLE
Add Inference Viewpoint Adapter

### PR DESCRIPTION
**Pull request by topnessman**
This is the viewpoint adapter changes in https://github.com/opprop/checker-framework/pull/69 at inference side. Travis test is expected to fail because dependent classes in the upstream haven't been merged yet. Should rerun the test after https://github.com/opprop/checker-framework/pull/69 passed.

### CODE REVIEW

**Comment by topnessman** [comment]
Travis test is expected to fail because dependent classes in the upstream haven't been merged yet. Should rerun the test after https://github.com/opprop/checker-framework/pull/69 passed.

**Comment by jyluo** [comment]
@topnessman upstream is merged. is this PR ready for review?

**Comment by topnessman** [comment]
@jyluo Let me try to clean up code duplicate, and then I'll ping you. Thanks.

**Comment by topnessman** [comment]
@jyluo Ready to review now.

**Comment by jyluo** [comment]
Looks good to me!

**Pull request merged**
