### PR TITLE
Update to EISOP

### PR DESCRIPTION
**Pull request by Ao-senXiong**
This is the attempt to update opprop checker-framework-inference project to based on the newest version of eisop check-framework.

### CODE REVIEW

**Comment by Ao-senXiong** [comment]
@wmdietl Hi Werner, can you take a look at this PR? I am not sure how to change the downstream tasks to pass all the checks. It seems that some inference failed.

**Comment by wmdietl** [comment]
Thanks for working on this!
I would suggest splitting this up into multiple PRs. opprop/cf is currently on Version 3.28.0-eisop1. Make a separate PR for each EISOP release since then and make sure that each upgrade individually works. This will make it easier to see at what point this issue is introduced and will make the history in opprop/cf easier to reproduce.
So start with an update to 3.32.0-eisop1 and have corresponding branches in all opprop repositories.
Does that sound like a good approach?

**Comment by Ao-senXiong** [comment]
> Thanks for working on this! I would suggest splitting this up into multiple PRs. opprop/cf is currently on Version 3.28.0-eisop1. Make a separate PR for each EISOP release since then and make sure that each upgrade individually works. This will make it easier to see at what point this issue is introduced and will make the history in opprop/cf easier to reproduce. So start with an update to 3.32.0-eisop1 and have corresponding branches in all opprop repositories. Does that sound like a good approach?

OK, sounds good. Thanks for the advice.

**Comment by Ao-senXiong** [comment]
Close as there is a new PR https://github.com/opprop/checker-framework-inference/pull/435.

**Pull request closed without merging**
